version: "3.6"
services:
  postgres:
    image: mdillon/postgis:latest
    # image: postgres
    container_name: postgres_genesis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/genesis/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    labels:
      - "traefik.enable=false"
    networks:
      - backend
  # end::postgres[]
  # tag::hasura[]
  hasura:
    image: hasura/graphql-engine:v1.2.1
    container_name: hasura_genesis
    ports:
      - ${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE:-true} # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:-genesis@Xtrios}
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_SERVER_PORT:-9091}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"${HASURA_GRAPHQL_JWT_SECRET}"}'
      # HASURA_GRAPHQL_AUTH_HOOK: ${HASURA_GRAPHQL_AUTH_HOOK:-http://localhost:4000/auth/hasura}
      # HASURA_GRAPHQL_AUTH_HOOK_MODE: ${HASURA_GRAPHQL_AUTH_HOOK_MODE:-POST}
      HASURA_GRAPHQL_CORS_DOMAIN: ${HASURA_GRAPHQL_CORS_DOMAIN:-https://*.myhistoryproject.com,http://*.myhistoryproject.com,http://localhost:5000,http://localhost:3000,http://localhost:9695}
      HASURA_GRAPHQL_CUSTOM_API: ${HASURA_GRAPHQL_CUSTOM_API:-http://localhost:4000/graphql}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES:-startup,http-log,webhook-log,websocket-log}
    labels:
      - "traefik.port=9091"
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`hasura.genesis.dev`)"
      - "traefik.http.routers.hasura.entrypoints=websecure"
      - "traefik.http.routers.hasura.tls.certresolver=myresolver"
    networks:
      - web
      - backend
  pgadmin:
    container_name: pgadmin_container
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@genesis.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - "hasura"
      - "postgres"
    networks:
      - backend
volumes:
  db_data:
  pgadmin:
networks:
  web:
    external: true
  backend:
    external: false
